# site settings
title: Nicolas Perraut
subtitle: Dev projects
email: n.perraut+gh@gmail.com
description: Nicolas' open source dev projects
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Nicolas Perraut
#permalink: project/:title

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 600

# social settings
500px_url:
facebook_url:
github_url: https://github.com/tuarrep
github_username: tuarrep
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/nicolas-perraut/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/NPerraut

# build settings
markdown: kramdown

sass:
  style: compressed
